channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.17.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.5.0
  - scipy==1.13.1
name: mlflow-env
